In [1]:
import pandas as pd
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import pickle

In [2]:
df = pd.read_csv('COVID.csv')

In [3]:
df

,Gender,Age,Nocomorbidity,Cardiovascular,Endocrine,tumor,Respiratory,Digestive,Renal,Liver,Fever,Cough,Chest tightness,Fatigue,Diarrhea,RNA,COVID
0,1,-1,1,0,0,0,0,0,0,0,1,1,1,1,1,0,1
1,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,1,1
2,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,1,1
3,1,-1,0,0,0,0,0,0,0,1,1,1,1,1,0,0,0
4,1,1,0,0,0,0,1,1,0,0,1,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,0,-2,1,0,0,0,0,0,0,0,1,1,0,0,0,1,1
85,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,1,1
86,0,2,0,1,0,0,0,0,0,0,0,1,0,0,0,1,1
87,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,1,1
88,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,1,1

In [4]:
df.shape

(89, 17)

In [5]:
train, test = train_test_split(df, test_size=0.3)

In [6]:
print(train.shape)

(62, 17)

In [7]:
print(test.shape)

(27, 17)

In [8]:
train_x = train[['Gender','Age', 'Nocomorbidity','Cardiovascular','Endocrine', 'tumor', 'Respiratory', 'Digestive', 'Renal', 'Liver', 'Fever', 'Cough', 'Chest tightness', 'Fatigue', 'Diarrhea', 'RNA']]
train_y = train.COVID

In [9]:
test_x = train[['Gender','Age', 'Nocomorbidity','Cardiovascular','Endocrine', 'tumor', 'Respiratory', 'Digestive', 'Renal', 'Liver', 'Fever', 'Cough', 'Chest tightness', 'Fatigue', 'Diarrhea', 'RNA']]
test_y = train.COVID

In [10]:
train_x.head()

,Gender,Age,Nocomorbidity,Cardiovascular,Endocrine,tumor,Respiratory,Digestive,Renal,Liver,Fever,Cough,Chest tightness,Fatigue,Diarrhea,RNA
11,1,1,0,0,0,0,0,0,0,0,1,1,1,0,0,0
49,1,-1,1,0,0,0,0,0,0,0,1,1,0,0,0,1
68,0,-1,1,0,0,0,0,0,0,0,1,0,0,0,0,1
46,1,1,0,1,0,0,0,0,0,0,1,1,0,0,0,1
1,0,0,1,0,0,0,0,0,0,0,1,1,1,0,0,1

In [11]:
train_y.head()

11    0
49    1
68    1
46    1
1     1
Name: COVID, dtype: int64

In [12]:
knn = KNeighborsClassifier(n_neighbors=16)
knn.fit(train_x, train_y)

KNeighborsClassifier(n_neighbors=16)

In [13]:
prediction = knn.predict(test_x)

In [14]:
print("Accuracy:",metrics.accuracy_score(prediction, test_y))

Accuracy: 0.8548387096774194

In [15]:
pickle.dump(knn,open('covid.pkl','wb'))